Adding Py Dependency
AnacondaRecipes/pytest-flake8-feedstock pull request #1
Opened 2023-10-20 20:02 UTC by psteyer

Adding Py dependency see following Jira ticket for more information:
https://anaconda.atlassian.net/browse/CVE-566

## changes
- adding `py`

2023-10-20 20:03 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: clone/recipe/meta.yaml:16: avoid_noarch: noarch: python packages should be avoided
ERROR: clone/recipe/meta.yaml:16: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
ERROR: clone/recipe/meta.yaml:22: missing_wheel: For pypi packages, wheel should be present in the host section
WARNING: clone/recipe/meta.yaml:25: python_build_tool_in_run: The python build tool setuptools is in run depends
ERROR: clone/recipe/meta.yaml:34: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: clone/recipe/meta.yaml:41: missing_description: The recipe is missing a description
ERROR: clone/recipe/meta.yaml:41: missing_documentation: The recipe is missing a doc_url or doc_source_url
ERROR: clone/recipe/meta.yaml:41: missing_dev_url: The recipe is missing a dev_url
Errors were found

</details>

2023-10-20 21:46 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:16: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
ERROR: clone/recipe/meta.yaml:22: missing_wheel: For pypi packages, wheel should be present in the host section
WARNING: clone/recipe/meta.yaml:25: python_build_tool_in_run: The python build tool setuptools is in run depends
ERROR: clone/recipe/meta.yaml:34: missing_pip_check: For pypi packages, pip check should be present in the test commands
WARNING: clone/recipe/meta.yaml:41: missing_description: The recipe is missing a description
ERROR: clone/recipe/meta.yaml:41: missing_dev_url: The recipe is missing a dev_url
ERROR: clone/recipe/meta.yaml:41: missing_documentation: The recipe is missing a doc_url or doc_source_url
Errors were found

</details>

2023-10-20 23:57 UTC, ryanskeith requested changes
It seems direct py support is only for testing and not runtime.  This should not be added.  Also, this is a few version behind.

2023-10-23 08:52 UTC, skupr-anaconda commented
I would suggest to update it to v1.1.1.

2023-10-24 22:09 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

ERROR: clone/recipe/meta.yaml:16: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
ERROR: clone/recipe/meta.yaml:22: missing_wheel: For pypi packages, wheel should be present in the host section
WARNING: clone/recipe/meta.yaml:25: python_build_tool_in_run: The python build tool setuptools is in run depends
ERROR: clone/recipe/meta.yaml:35: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: clone/recipe/meta.yaml:42: missing_documentation: The recipe is missing a doc_url or doc_source_url
ERROR: clone/recipe/meta.yaml:42: missing_dev_url: The recipe is missing a dev_url
WARNING: clone/recipe/meta.yaml:42: missing_description: The recipe is missing a description
Errors were found

</details>

2023-10-24 22:41 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: clone/recipe/meta.yaml:16: avoid_noarch: noarch: python packages should be avoided
ERROR: clone/recipe/meta.yaml:16: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
ERROR: clone/recipe/meta.yaml:22: missing_wheel: For pypi packages, wheel should be present in the host section
WARNING: clone/recipe/meta.yaml:25: python_build_tool_in_run: The python build tool setuptools is in run depends
ERROR: clone/recipe/meta.yaml:35: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: clone/recipe/meta.yaml:42: missing_dev_url: The recipe is missing a dev_url
ERROR: clone/recipe/meta.yaml:42: missing_documentation: The recipe is missing a doc_url or doc_source_url
WARNING: clone/recipe/meta.yaml:42: missing_description: The recipe is missing a description
Errors were found

</details>

2023-10-25 06:01 UTC, skupr-anaconda approved these changes

2023-10-27 16:03 UTC, ryanskeith approved these changes
LGTM

2023-10-27 16:26 UTC, merged

2023-10-27 16:27 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
The following problems have been found:

WARNING: clone/recipe/meta.yaml:16: avoid_noarch: noarch: python packages should be avoided
ERROR: clone/recipe/meta.yaml:16: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
ERROR: clone/recipe/meta.yaml:22: missing_wheel: For pypi packages, wheel should be present in the host section
WARNING: clone/recipe/meta.yaml:25: python_build_tool_in_run: The python build tool setuptools is in run depends
ERROR: clone/recipe/meta.yaml:35: missing_pip_check: For pypi packages, pip check should be present in the test commands
ERROR: clone/recipe/meta.yaml:42: missing_dev_url: The recipe is missing a dev_url
WARNING: clone/recipe/meta.yaml:42: missing_description: The recipe is missing a description
ERROR: clone/recipe/meta.yaml:42: missing_documentation: The recipe is missing a doc_url or doc_source_url
Errors were found

</details>